# Matrix

In [2]:
import numpy as np

In [3]:
# craete 2*3  matrix
a = np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# craete a matrix of big dimention
import numpy as np
matrix = np.arange(0, 100, 2)
matrix

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [12]:
matrix = np.arange(0, 100, 2).reshape(5,10)
matrix

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [ ]:
# Slicing a matrix
matrix[1:3,3:5]

array([[26, 28],
       [46, 48]])

In [14]:
matrix.max()

np.int64(98)

In [19]:
matrix.max(axis=0) # 0 only for columns

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [20]:
matrix.max(axis=1) # 1 only for rows

array([18, 38, 58, 78, 98])

In [21]:
matrix.min()

np.int64(0)

In [22]:
matrix.sum()

np.int64(2450)

In [25]:
matrix

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [31]:
np.flip(matrix)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])