# Linear Algabra in Python

In [1]:
import numpy as np


In [11]:
# coefficients of matrix A
A = np.array([[2, 3], [5, 4]])

In [12]:
A

array([[2, 3],
       [5, 4]])

In [13]:
# constants matrix B
B = np.array([8,20])

In [14]:
B

array([ 8, 20])

In [15]:
# solve for x
x = np.linalg.solve(A, B) # this will give you the values of x1 and x2
x

array([ 4.00000000e+00, -3.17206578e-16])