# Numpy


In [47]:
import numpy as np
a = np.arange(6)
print (a)


[0 1 2 3 4 5]


In [48]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [49]:
a2.shape

(1, 6)

In [50]:
a2 = a[ :, np.newaxis]
print(a2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [51]:
a2.shape

(6, 1)

In [52]:
a3 = a2[np.newaxis, :]
print(a3)

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


In [53]:
a3.dtype

dtype('int64')

In [54]:
a3.shape

(1, 6, 1)

# Creating New Arrays

In [55]:
a= np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7),(8,1,2,3,4,5,6)])

In [56]:
a.shape


(7,)

In [57]:
b.shape

(2, 7)

# initialize Array


In [58]:
zeros = np.zeros((30,4)) # Rows , Columns
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
ones = np.ones((30,4)) # Rows , Columns
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
desire = np.full((3,4), 5) # Rows , Columns
desire

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [61]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
identity.dtype

dtype('float64')

In [63]:
type(identity)

numpy.ndarray

# Attribtes of Array

In [69]:
a.shape # this for know the shape of the array

(7,)

In [70]:
len(a) # this for know the length of the list

7

In [71]:
a.ndim # This is for know the number of dimensions of the array

1

In [72]:
a.size # this will return the number of elements in the array

7