# Numpy (Part 2)

In [1]:
import numpy as np

In [5]:
empty = np.empty((2,4))
print(empty)
print("--------------------")
print(empty[0])

[[1.01039396e-311 1.01039396e-311 1.01039396e-311 4.94065646e-324]
 [1.01040816e-311 0.00000000e+000 0.00000000e+000 7.41098469e-323]]
--------------------
[1.01039396e-311 1.01039396e-311 1.01039396e-311 4.94065646e-324]


In [6]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [7]:
even = np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [8]:
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [12]:
# specific different
diff = np.arange(0,23,1.1) # 1.1 is the step size
diff

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ,
       12.1, 13.2, 14.3, 15.4, 16.5, 17.6, 18.7, 19.8, 20.9, 22. ])

In [26]:
lin = np.linspace(0, 10, num=10) # linspace is used to generate 10 evenly spaced numbers from 0 to 20
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [31]:
arr = np.array([3,5,45,565564,342,54])
np.sort(arr)

array([     3,      5,     45,     54,    342, 565564])

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
# Concatination
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2D Dimentional Array

In [42]:
x = np.array([[1,2,3,4,5],[9,6,7,4,3]])
y = np.array([[6,7,8,9,10]])

In [43]:
z = np.concatenate((x,y), axis=0)

In [44]:
z

array([[ 1,  2,  3,  4,  5],
       [ 9,  6,  7,  4,  3],
       [ 6,  7,  8,  9, 10]])

# 3D Dimentional Array

In [47]:
# create 3D array with give themself values
arr = np.array([[[1, 2, 3], [4, 5, 4],[7, 8, 9]]])
# second array
arr2 = np.array([[[1, 3, 3], [6, 5, 4],[3, 8, 9]]])
np.concatenate((arr, arr2))


array([[[1, 2, 3],
        [4, 5, 4],
        [7, 8, 9]],

       [[1, 3, 3],
        [6, 5, 4],
        [3, 8, 9]]])

In [48]:
arr.ndim

3